-- Sample seed properties for testing the property data management system
-- This script creates some example properties that can be claimed by sellers

-- Insert sample seed properties
INSERT INTO public.properties (
  id,
  seller_id, -- NULL for seed properties
  title,
  description,
  address,
  city,
  state,
  zip_code,
  price_per_night,
  bedrooms,
  bathrooms,
  square_feet,
  listing_price,
  year_built,
  lot_acres,
  hoa_fee,
  property_type,
  mls_id,
  source_feed_id,
  list_date,
  days_on_market,
  is_seed_property,
  property_features,
  location_community,
  building_info,
  lot_info,
  interior_features,
  images,
  original_image_urls,
  is_active,
  verification_status,
  created_at,
  updated_at
) VALUES 
(
  uuid_generate_v4(),
  NULL, -- Seed property, no seller
  'Modern Prairie Estate',
  'Stunning modern prairie-style home with open floor plan and premium finishes. Features vaulted ceilings, hardwood floors, and a gourmet kitchen with quartz countertops.',
  '1234 Oak Street',
  'Portland',
  'OR',
  '97201',
  450,
  4,
  3.5,
  3850,
  1850000,
  2020,
  0.16,
  25.00,
  'Single Family',
  'MLS123456',
  'feed_001',
  '2025-01-01T00:00:00Z',
  15,
  true,
  '{"beds": 4, "full_baths": 3, "half_baths": 1, "garage": 2, "style": "Modern Prairie", "year_built": 2020}'::jsonb,
  '{"property_type": "Single Family", "hoa": true, "hoa_fee": 25, "county": "Multnomah", "neighborhood": "Pearl District"}'::jsonb,
  '{"above_grade_size": 3850, "total_size": 3850, "foundation_details": "Slab", "building_exterior_type": "Brick, Cement Siding"}'::jsonb,
  '{"lot_acres": 0.16, "lot_sqft": 6969, "lot_features": "Built-in Hot Tub, Covered Deck, Fenced Yard"}'::jsonb,
  '["Hardwood Floors", "Vaulted Ceilings", "Quartz Countertops", "Stainless Steel Appliances", "Central Air", "Garage Door Opener"]'::jsonb,
  ARRAY['https://example.com/image1.jpg', 'https://example.com/image2.jpg'],
  ARRAY['https://original-feed.com/image1.jpg', 'https://original-feed.com/image2.jpg'],
  true,
  'approved',
  NOW(),
  NOW()
),
(
  uuid_generate_v4(),
  NULL, -- Seed property, no seller
  'Charming Victorian Home',
  'Beautiful Victorian home with original character and modern updates. Features hardwood floors, updated kitchen, and a lovely garden.',
  '5678 Pine Avenue',
  'Seattle',
  'WA',
  '98101',
  350,
  3,
  2.0,
  2200,
  850000,
  1895,
  0.12,
  NULL,
  'Single Family',
  'MLS789012',
  'feed_001',
  '2025-01-02T00:00:00Z',
  8,
  true,
  '{"beds": 3, "full_baths": 2, "half_baths": 0, "garage": 1, "style": "Victorian", "year_built": 1895}'::jsonb,
  '{"property_type": "Single Family", "hoa": false, "county": "King", "neighborhood": "Capitol Hill"}'::jsonb,
  '{"above_grade_size": 2200, "total_size": 2200, "foundation_details": "Basement", "building_exterior_type": "Wood Siding"}'::jsonb,
  '{"lot_acres": 0.12, "lot_sqft": 5227, "lot_features": "Garden, Patio, Mature Trees"}'::jsonb,
  '["Hardwood Floors", "Original Woodwork", "Updated Kitchen", "Clawfoot Tub", "Bay Windows"]'::jsonb,
  ARRAY['https://example.com/victorian1.jpg', 'https://example.com/victorian2.jpg'],
  ARRAY['https://original-feed.com/victorian1.jpg', 'https://original-feed.com/victorian2.jpg'],
  true,
  'approved',
  NOW(),
  NOW()
),
(
  uuid_generate_v4(),
  NULL, -- Seed property, no seller
  'Luxury Downtown Condo',
  'High-end downtown condo with city views, premium amenities, and modern finishes. Perfect for urban living.',
  '9999 Main Street, Unit 15B',
  'San Francisco',
  'CA',
  '94102',
  600,
  2,
  2.0,
  1800,
  1200000,
  2018,
  NULL,
  450.00,
  'Condo',
  'MLS345678',
  'feed_001',
  '2025-01-03T00:00:00Z',
  22,
  true,
  '{"beds": 2, "full_baths": 2, "half_baths": 0, "garage": 1, "style": "Modern", "year_built": 2018}'::jsonb,
  '{"property_type": "Condo", "hoa": true, "hoa_fee": 450, "county": "San Francisco", "neighborhood": "Financial District"}'::jsonb,
  '{"above_grade_size": 1800, "total_size": 1800, "foundation_details": "Concrete", "building_exterior_type": "Glass, Steel"}'::jsonb,
  '{"lot_features": "City Views, Balcony"}'::jsonb,
  '["Hardwood Floors", "Granite Countertops", "Stainless Steel Appliances", "In-Unit Laundry", "Floor-to-Ceiling Windows"]'::jsonb,
  ARRAY['https://example.com/condo1.jpg', 'https://example.com/condo2.jpg'],
  ARRAY['https://original-feed.com/condo1.jpg', 'https://original-feed.com/condo2.jpg'],
  true,
  'approved',
  NOW(),
  NOW()
);

-- Create a sample property import record
INSERT INTO public.property_imports (
  admin_id,
  import_type,
  source_file,
  properties_processed,
  properties_created,
  properties_updated,
  properties_errors,
  import_status,
  created_at,
  updated_at
) VALUES (
  (SELECT id FROM public.profiles WHERE role = 'superadmin' LIMIT 1),
  'feed',
  'sample_properties_feed.json',
  3,
  3,
  0,
  0,
  'success',
  NOW(),
  NOW()
);
